<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Fiche15 extends Model
{
    use HasFactory, HasUuids;
    protected $table = 'reponse_fiche15';
    protected $keyType = 'string';
    protected $fillable =  [
        'id',
        'cin',
        'UUID_BDC',
        'createur',
        'noteQ1',
        'valeur_id_NoteQ1',
        'noteQ2',
        'valeur_id_NoteQ2',
        'noteQ3',
        'valeur_id_NoteQ3',
        'noteQ4',
        'valeur_id_NoteQ4',
        'noteQ5',
        'valeur_id_NoteQ5',
        'noteQ6',
        'valeur_id_NoteQ6',
        'noteQ7',
        'valeur_id_NoteQ7',
        'noteQ8',
        'valeur_id_NoteQ8',
        'noteQ9',
        'valeur_id_NoteQ9',
        'noteQ10',
        'valeur_id_NoteQ10',
        'noteQ11',
        'valeur_id_NoteQ11',
        'noteQ12',
        'valeur_id_NoteQ12',
        'noteQ13',
        'valeur_id_NoteQ13',
        'noteQ14',
        'valeur_id_NoteQ14',
        'noteQ15',
        'valeur_id_NoteQ15',
        'noteQ16',
        'valeur_id_NoteQ16',
        'noteQ17',
        'valeur_id_NoteQ17',
        'noteQ18',
        'valeur_id_NoteQ18',
        'noteQ19',
        'valeur_id_NoteQ19',
        'noteQ20',
        'valeur_id_NoteQ20',
        'noteQ21',
        'valeur_id_NoteQ21',
        'noteQ22',
        'valeur_id_NoteQ22',
        'noteQ23',
        'valeur_id_NoteQ23',
        'noteQ24',
        'valeur_id_NoteQ24',
        'noteQ25',
        'valeur_id_NoteQ25',
        'noteQ26',
        'valeur_id_NoteQ26',
        'noteQ27',
        'valeur_id_NoteQ27',
        'noteQ28',
        'valeur_id_NoteQ28',
        'noteQ29',
        'valeur_id_NoteQ29',
        'noteQ30',
        'valeur_id_NoteQ30',
        'noteQ31',
        'valeur_id_NoteQ31',
        'noteQ32',
        'valeur_id_NoteQ32',
        'noteQ33',
        'valeur_id_NoteQ33',
        'noteQ34',
        'valeur_id_NoteQ34',
        'noteQ35',
        'valeur_id_NoteQ35',
        'noteQ36',
        'valeur_id_NoteQ36',
    ];
}
