<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Fiche14 extends Model
{
    use HasFactory, HasUuids;
    protected $table = 'reponse_fiche14';
    protected $keyType = 'string';
    protected $fillable =  [
        'id',
        'cin',
        'UUID_BDC',
        'createur',
        'noteQ1',
        'noteQ2',
        'noteQ3',
        'noteQ4',
        'noteQ5',
        'noteQ6',
        'noteQ7',
        'noteQ8',
        'noteQ9',
        'noteQ10',
        'noteQ11',
        'noteQ12',
        'noteQ13',
        'noteQ14',
        'noteQ15',
        'noteQ16',
        'noteQ17',
        'noteQ18',
        'noteQ19',
        'noteQ20',
        'noteQ21',
        'noteQ22',
        'noteQ23',
        'noteQ24',
        'noteQ25',
        'noteQ26',
        'noteQ27',
        'noteQ28',
        'noteQ29',
        'noteQ30',
        'noteQ31',
        'noteQ32',
        'noteQ33',
        'noteQ34',
        'noteQ35',
        'noteQ36',
        'noteQ37',
        'noteQ38',
        'noteQ39',
        'noteQ40',
        'noteQ41',
        'noteQ42',
        'noteQ43',
        'noteQ44',
        'noteQ45',
        'noteQ46',
        'noteQ47',
        'noteQ48',
        'noteQ49',
        'noteQ50',
        'noteQ51',
        'noteQ52',
        'noteQ53',
        'noteQ54',
        'noteQ55',
        'noteQ56',
        'noteQ57',
        'noteQ58',
        'noteQ59',
        'noteQ60',
        'noteQ61',
        'noteQ62',
        'noteQ63',
        'noteQ64',
        'noteQ65',
        'noteQ66',
        'noteQ67',
        'noteQ68',
        'noteQ69',
        'noteQ70',
        'noteQ1Group',
    ];
}
